/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/HoleMask.gltf
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import * as THREE from "three";

const HoleMask = (props) => {
  const { nodes, materials } = useGLTF("/Models/HoleMask.gltf");

  const Kakel = materials["Old Tiles"];



  let material = new THREE.MeshBasicMaterial({
    color: 0x000000,
    colorWrite: false,
  });

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry}>
        <meshBasicMaterial {...Kakel} />
      </mesh>
      <mesh geometry={nodes.CubeMask.geometry} material={material} />
    </group>
  );
};

export default HoleMask;

useGLTF.preload("/Models/HoleMask.gltf");
